config/routes.rb
Rails.application.routes.draw do
  resources :settings
  resources :daily_transaction_details
  resources :currencies
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  get 'dashboard' => 'home#dashboard'
  get 'accounts_tree' => 'accounts#accounts_tree'
  post 'search_accounts' => 'daily_transactions#search_accounts'
  post 'transaction_details' => 'daily_transactions#transaction_details'
  get 'draw_trial_balance' => 'trial_balance#get_datatable'
  post 'export_trial_balance' => 'trial_balance#export_trial_balance'
  get 'export_pdf' => 'trial_balance#export_pdf'

  


  get 'trial_balance' => 'trial_balance#index'

  get 'account_statements' => 'account_statements#index'
  get 'draw_account_statement' => 'account_statements#draw_account_statement'
  get 'draw_currencies' => 'currencies#draw_currencies'


  resources :cost_centers do
    collection do 
      get :trial_balance
      get :get_datatable
      get :account_statements
      get :get_account_statement
    end
  end


  resources :accounts do
    collection { 
      post :import 
      get :export_form
    }
  end

  resources :daily_transactions do
    collection { post :import }
  end
  
end

app/models/daily_transaction_detail.rb
class DailyTransactionDetail < ApplicationRecord
  belongs_to :daily_transaction
  belongs_to :account
  belongs_to :cost_center, optional: true
  belongs_to :currency, optional: true

  before_create :default_currency
  before_save :default_values
  def default_values
    if self.cost_center_id == 0
      self.cost_center_id = nil
    end
    if self.currency_id == 0
      self.currency_id = nil
    end    
  end

  def default_currency
    self.default_currency = Setting.find_by_key('default_currency').value
    self.currency_rate = Currency.find_by_id(currency_id).rate
  end

end

app/controllers/daily_transaction_details_controller.rb
class DailyTransactionDetailsController < ApplicationController
  before_action :set_daily_transaction_detail, only: %i[ show edit update destroy ]

  # GET /daily_transaction_details or /daily_transaction_details.json
  def index
    @daily_transaction_details = DailyTransactionDetail.all
  end

  # GET /daily_transaction_details/1 or /daily_transaction_details/1.json
  def show
  end

  # GET /daily_transaction_details/new
  def new
    @daily_transaction_detail = DailyTransactionDetail.new
  end

  # GET /daily_transaction_details/1/edit
  def edit
  end

  # POST /daily_transaction_details or /daily_transaction_details.json
  def create
    @daily_transaction_detail = DailyTransactionDetail.new(daily_transaction_detail_params)

    respond_to do |format|
      if @daily_transaction_detail.save
        format.html { redirect_to daily_transaction_detail_url(@daily_transaction_detail), notice: "Daily transaction detail was successfully created." }
        format.json { render :show, status: :created, location: @daily_transaction_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @daily_transaction_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_transaction_details/1 or /daily_transaction_details/1.json
  def update
    respond_to do |format|
      if @daily_transaction_detail.update(daily_transaction_detail_params)
        format.html { redirect_to daily_transaction_detail_url(@daily_transaction_detail), notice: "Daily transaction detail was successfully updated." }
        format.json { render :show, status: :ok, location: @daily_transaction_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @daily_transaction_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_transaction_details/1 or /daily_transaction_details/1.json
  def destroy
    @daily_transaction_detail.destroy

    respond_to do |format|
      format.html { redirect_to daily_transaction_details_url, notice: "Daily transaction detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_transaction_detail
      @daily_transaction_detail = DailyTransactionDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def daily_transaction_detail_params
      params.require(:daily_transaction_detail).permit(:daily_transaction_id, :account_id, :cost_center_id, :currency_id, :description, :debit, :credit, :item_date, :currency_rate)
    end
end

app/helpers/daily_transaction_details_helper.rb
module DailyTransactionDetailsHelper
end

app/views/daily_transaction_details/_daily_transaction_detail.html.erb
<div id="<%= dom_id daily_transaction_detail %>">
  <p>
    <strong>Daily transaction:</strong>
    <%= daily_transaction_detail.daily_transaction_id %>
  </p>

  <p>
    <strong>Account:</strong>
    <%= daily_transaction_detail.account_id %>
  </p>

  <p>
    <strong>Cost center:</strong>
    <%= daily_transaction_detail.cost_center_id %>
  </p>

  <p>
    <strong>Currency:</strong>
    <%= daily_transaction_detail.currency_id %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= daily_transaction_detail.description %>
  </p>

  <p>
    <strong>Debit:</strong>
    <%= daily_transaction_detail.debit %>
  </p>

  <p>
    <strong>Credit:</strong>
    <%= daily_transaction_detail.credit %>
  </p>

  <p>
    <strong>Item date:</strong>
    <%= daily_transaction_detail.item_date %>
  </p>

</div>

app/views/daily_transaction_details/_form.html.erb
<%= form_with(model: daily_transaction_detail) do |form| %>
  <% if daily_transaction_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(daily_transaction_detail.errors.count, "error") %> prohibited this daily_transaction_detail from being saved:</h2>

      <ul>
        <% daily_transaction_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :daily_transaction_id, style: "display: block" %>
    <%= form.text_field :daily_transaction_id %>
  </div>

  <div>
    <%= form.label :account_id, style: "display: block" %>
    <%= form.text_field :account_id %>
  </div>

  <div>
    <%= form.label :cost_center_id, style: "display: block" %>
    <%= form.text_field :cost_center_id %>
  </div>

  <div>
    <%= form.label :currency_id, style: "display: block" %>
    <%= form.text_field :currency_id %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :debit, style: "display: block" %>
    <%= form.text_field :debit %>
  </div>

  <div>
    <%= form.label :credit, style: "display: block" %>
    <%= form.text_field :credit %>
  </div>

  <div>
    <%= form.label :item_date, style: "display: block" %>
    <%= form.date_field :item_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/daily_transaction_details/edit.html.erb
<h1>Editing daily transaction detail</h1>

<%= render "form", daily_transaction_detail: @daily_transaction_detail %>

<br>

<div>
  <%= link_to "Show this daily transaction detail", @daily_transaction_detail %> |
  <%= link_to "Back to daily transaction details", daily_transaction_details_path %>
</div>

app/views/daily_transaction_details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Daily transaction details</h1>

<div id="daily_transaction_details">
  <% @daily_transaction_details.each do |daily_transaction_detail| %>
    <%= render daily_transaction_detail %>
    <p>
      <%= link_to "Show this daily transaction detail", daily_transaction_detail %>
    </p>
  <% end %>
</div>

<%= link_to "New daily transaction detail", new_daily_transaction_detail_path %>

app/views/daily_transaction_details/new.html.erb
<h1>New daily transaction detail</h1>

<%= render "form", daily_transaction_detail: @daily_transaction_detail %>

<br>

<div>
  <%= link_to "Back to daily transaction details", daily_transaction_details_path %>
</div>

app/views/daily_transaction_details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @daily_transaction_detail %>

<div>
  <%= link_to "Edit this daily transaction detail", edit_daily_transaction_detail_path(@daily_transaction_detail) %> |
  <%= link_to "Back to daily transaction details", daily_transaction_details_path %>

  <%= button_to "Destroy this daily transaction detail", @daily_transaction_detail, method: :delete %>
</div>