config/routes.rb
Rails.application.routes.draw do
  resources :settings
  resources :daily_transaction_details
  resources :currencies
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  get 'dashboard' => 'home#dashboard'
  get 'accounts_tree' => 'accounts#accounts_tree'
  post 'search_accounts' => 'daily_transactions#search_accounts'
  post 'transaction_details' => 'daily_transactions#transaction_details'
  get 'draw_trial_balance' => 'trial_balance#get_datatable'
  post 'export_trial_balance' => 'trial_balance#export_trial_balance'
  get 'export_pdf' => 'trial_balance#export_pdf'

  


  get 'trial_balance' => 'trial_balance#index'

  get 'account_statements' => 'account_statements#index'
  get 'draw_account_statement' => 'account_statements#draw_account_statement'
  get 'draw_currencies' => 'currencies#draw_currencies'


  resources :cost_centers do
    collection do 
      get :trial_balance
      get :get_datatable
      get :account_statements
      get :get_account_statement
    end
  end


  resources :accounts do
    collection { 
      post :import 
      get :export_form
    }
  end

  resources :daily_transactions do
    collection { post :import }
  end
  
end

app/models/cost_center.rb
class CostCenter < ApplicationRecord

    has_ancestry cache_depth: true

    # to avoid n+1 problem
    has_many :cost_centers, foreign_key: :parent_center

    has_many :daily_transaction_details


    #counter_cache option can be used to make finding the number of belonging objects more efficient. Consider these models
    belongs_to :cost_center, counter_cache: true, foreign_key: :parent_center, optional: true
    validates_presence_of :name_ar

    before_validation do
        self.ancestry = nil if self.ancestry.blank?
        self.parent_center = nil if self.parent_center.blank?
    end

    def self.json_tree(nodes)
        nodes.map do |node, sub_nodes|
          {:text => node.name_ar, :id => node.id, :children => CostCenter.json_tree(sub_nodes).compact}
        end
    end
end

app/controllers/cost_centers_controller.rb
class CostCentersController < ApplicationController
  before_action :set_cost_center, only: %i[ show edit update destroy ]

  # GET /cost_centers or /cost_centers.json
  def index
    @cost_centers = CostCenter.all
    @cost_centers_arranged = CostCenter.arrange
    respond_to do |format|
      format.html { @cost_centers = CostCenter.all }
      format.json { render json: CostCenter.json_tree(@cost_centers_arranged)}
    end
  end

  def trial_balance
  end

  def get_datatable
    #sum all trans for all cost centers
    @cost_centers = CostCenter.order(:code).all   
    @hash = CostCenter.includes(:daily_transaction_details).group('cost_centers.id').pluck('cost_centers.id, SUM(daily_transaction_details.debit)', 'SUM(daily_transaction_details.credit)')
    
    #puts @hash
    
    @familiar_array = {}
    @get_cost_centers_data = @cost_centers.pluck(:id, :parent_center, :ancestry)
    #sum_children_transactions
    @cost_centers.each do |cost_center|
        if(cost_center.ancestry == nil)
            @childrenIds = @get_cost_centers_data.find_all { |el| ( (el[0] == cost_center.id) ||  ( (el[2] != nil) && ((el[2] == cost_center.id.to_s) ||  el[2].start_with?(cost_center.id.to_s + "/") ))) } # a.select will do the same
        else
            @childrenIds = @get_cost_centers_data.find_all { |el| (  (el[0] == cost_center.id) || ( (el[2] != nil) && ((el[2] == cost_center.id.to_s) ||  el[2].start_with?(cost_center.ancestry.to_s + "/"  + cost_center.id.to_s)))) } # a.select will do the same
        end
        @familiar_array[cost_center.id] = [0.00,0.00]

        @childrenIds.each do |child|
            @child_id = child[0]
            $total_trans = @hash.detect{ |(n, _, _)| ((n == @child_id)) }
            @familiar_array[cost_center.id][0] += ($total_trans[1] == nil)? 0.00 : $total_trans[1]   
            @familiar_array[cost_center.id][1] += ($total_trans[2] == nil)? 0.00 : $total_trans[2]  
        end
        puts @familiar_array
    end

    if(!(params[:search].empty?))
        puts params[:search][:value]
        @search_text = params[:search][:value]
        @cost_centers = @cost_centers.where("name_ar LIKE ? OR name_en LIKE ? OR code LIKE ?", "%#{@search_text}%", "%#{@search_text}%" , "%#{@search_text}%")
    end

    if(!(params[:cost_center_id].nil?))
        @cost_centers = @cost_centers.where(id: params[:cost_center_id])
    end

    if(!(params[:level].empty?))
        @cost_centers = @cost_centers.before_depth(params[:level].to_i)
    end

    if(params[:main_accounts] == "false")           #display last node in each branch
        @cost_centers = @cost_centers.includes(:cost_centers).where(cost_centers_count: 0)
    end

    @results = {}
    @count_records = @cost_centers.count
    @results["draw"] = params[:draw].to_i
    @results["recordsTotal"] = @count_records
    @results["recordsFiltered"] = @count_records
    @Length = (params[:length].to_i < 0)? @count_records : params[:length].to_i 
    @start = params[:start].to_i

    @cost_centers = @cost_centers.limit(@Length).offset(@start )
    @results["data"] = @cost_centers.map do |cost_center|
                            @debit = @familiar_array[cost_center.id][0]
            @credit = @familiar_array[cost_center.id][1]
            @difference = @debit - @credit
                            @balance_debit = (@difference > 0)?  @difference : 0
                            @balance_credit = (@difference < 0)?  @difference.abs : 0
                            @item = {"accountNumber" => cost_center.code, "nameAr" => cost_center.name_ar, "debit" => 0.00, "credit" => 0.00, "total_debit" => @debit, "total_credit" => @credit,"debit_balance" => @balance_debit, "credit_balance" => @balance_credit}
                            @item
                        end
    respond_to do |format|
      format.html
      format.json { render json: @results}
    end
  end


  def account_statements
  end

  def get_account_statement
    @results = {}
    @daily_transaction_details = DailyTransactionDetail.where.not(cost_center_id: nil).order(:item_date).includes(:daily_transaction, :account).all

    @count_records = @daily_transaction_details.count
    @results["draw"] = params[:draw].to_i
    @results["recordsTotal"] = @count_records
    @results["recordsFiltered"] = @count_records
    @Length = (params[:length].to_i < 0)? @count_records : params[:length].to_i 
    @start = params[:start].to_i

    @total_balance = 0;

    @daily_transaction_details = @daily_transaction_details.limit(@Length).offset(@start )
    @total_debit = 0
    @total_credit = 0

    @content = []
    @content << {"TranNo" => "الرصيد السابق", "description" => '', "debit" => '', "credit" => '', "balance" => '', "date" => ''}
    @daily_transaction_details.map do |daily_transaction_data|
      @debit = daily_transaction_data.debit
      @credit = daily_transaction_data.credit
      @total_balance = @total_balance + @debit - @credit

      @total_debit += @debit
      @total_credit += @credit
                      
      @item = {"TranNo" => daily_transaction_data.daily_transaction.id, "description" => daily_transaction_data.description, "debit" => @debit, "credit" => @credit, "balance" => @total_balance, "date" => daily_transaction_data.item_date}
      @content << @item
    end

    @content << {"TranNo" => "", "description" => 'المجموع', "debit" => @total_debit, "credit" => @total_credit, "balance" => @total_balance, "date" => ''}

    @results["data"] = @content
    respond_to do |format|
      format.html
      format.json { render json: @results}
    end
  end

  # GET /cost_centers/1 or /cost_centers/1.json
  def show
  end

  # GET /cost_centers/new
  def new
    @cost_center = CostCenter.new
  end

  # GET /cost_centers/1/edit
  def edit
  end

  # POST /cost_centers or /cost_centers.json
  def create
    params[:cost_center][:parent_center] = params[:cost_center][:ancestry]
    if(params[:cost_center][:ancestry] != nil && params[:cost_center][:ancestry]) != ''
      @parent = CostCenter.find_by_id(params[:cost_center][:ancestry])
      @grand_parent = @parent.ancestry
      if @grand_parent == nil
        params[:cost_center][:ancestry] = params[:cost_center][:ancestry]
      else
        params[:cost_center][:ancestry] = @grand_parent.to_s + "/" + params[:cost_center][:ancestry].to_s
      end
    end
    @cost_center = CostCenter.new(cost_center_params)
    if @cost_center.save
      render json: {"Success": true, result: t('saved_successfully')}
    else
      render json: {"Errors": true, result: @cost_center.errors}
    end 


  end

  # PATCH/PUT /cost_centers/1 or /cost_centers/1.json
  def update
    respond_to do |format|
      if @cost_center.update(cost_center_params)
        format.html { redirect_to cost_center_url(@cost_center), notice: "Cost center was successfully updated." }
        format.json { render :show, status: :ok, location: @cost_center }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cost_center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cost_centers/1 or /cost_centers/1.json
  def destroy
    @cost_center.destroy

    respond_to do |format|
      format.html { redirect_to cost_centers_url, notice: "Cost center was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost_center
      @cost_center = CostCenter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cost_center_params
      params.require(:cost_center).permit(:name_en, :name_ar, :parent_center, :status, :deleted, :deleted_by, :deleted_date, :created_by, :code, :ancestry, :ancestry_depth)
    end
end

app/helpers/cost_centers_helper.rb
module CostCentersHelper
    def nested_dropdown(items)
        result = []
        items.map do |item, sub_items|
            result << [('- ' * item.ancestry_depth) + item.name_ar, item.id]
            result += nested_dropdown(sub_items) unless sub_items.blank?
        end
        result
    end
end

app/views/cost_centers/_cost_center.html.erb
<div id="<%= dom_id cost_center %>">
  <p>
    <strong>Name en:</strong>
    <%= cost_center.name_en %>
  </p>

  <p>
    <strong>Name ar:</strong>
    <%= cost_center.name_ar %>
  </p>

  <p>
    <strong>Parent:</strong>
    <%= cost_center.parent %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= cost_center.status %>
  </p>

  <p>
    <strong>Deleted:</strong>
    <%= cost_center.deleted %>
  </p>

  <p>
    <strong>Deleted by:</strong>
    <%= cost_center.deleted_by %>
  </p>

  <p>
    <strong>Deleted date:</strong>
    <%= cost_center.deleted_date %>
  </p>

  <p>
    <strong>Created by:</strong>
    <%= cost_center.created_by %>
  </p>

</div>

app/views/cost_centers/_form.html.erb
<%= form_with(model: cost_center) do |form| %>
  <% if cost_center.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cost_center.errors.count, "error") %> prohibited this cost_center from being saved:</h2>

      <ul>
        <% cost_center.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name_en, style: "display: block" %>
    <%= form.text_field :name_en %>
  </div>

  <div>
    <%= form.label :name_ar, style: "display: block" %>
    <%= form.text_field :name_ar %>
  </div>

  <div>
    <%= form.label :parent, style: "display: block" %>
    <%= form.text_field :parent %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.check_box :status %>
  </div>

  <div>
    <%= form.label :deleted, style: "display: block" %>
    <%= form.check_box :deleted %>
  </div>

  <div>
    <%= form.label :deleted_by, style: "display: block" %>
    <%= form.number_field :deleted_by %>
  </div>

  <div>
    <%= form.label :deleted_date, style: "display: block" %>
    <%= form.datetime_field :deleted_date %>
  </div>

  <div>
    <%= form.label :created_by, style: "display: block" %>
    <%= form.number_field :created_by %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cost_centers/edit.html.erb
<h1>Editing cost center</h1>

<%= render "form", cost_center: @cost_center %>

<br>

<div>
  <%= link_to "Show this cost center", @cost_center %> |
  <%= link_to "Back to cost centers", cost_centers_path %>
</div>

app/views/cost_centers/index.html.erb
<!--begin::Content-->
  <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Container-->
    <div class="container-xxl" id="kt_content_container">
      <!--begin::Card-->
      <div class="card">
        <!--begin::Card body-->
        <div class="card-body">
            <a href="#" style="float:left;" class="btn btn-primary er fs-6 px-8 py-4" data-bs-toggle="modal" data-bs-target="#kt_modal_new_target">أضف مركز تكلفة</a>            
            <div id="kt_docs_jstree_ajax"></div>
          
        </div>

        <!--end::Card body-->
      </div>
      <!--end::Card-->
    </div>
    <!--end::Container-->

  </div>
<!--end::Content-->


<!--begin::Modal - New Target-->
<div class="modal fade" id="kt_modal_new_target" tabindex="-1" aria-hidden="true">
    <!--begin::Modal dialog-->
    <div class="modal-dialog modal-dialog-centered mw-650px">
        <!--begin::Modal content-->
        <div class="modal-content rounded">
            <!--begin::Modal header-->
            <div class="modal-header pb-0 border-0 justify-content-end">
                <!--begin::Close-->
                <div class="btn btn-sm btn-icon btn-active-color-primary" data-bs-dismiss="modal">
                    <!--begin::Svg Icon | path: icons/duotune/arrows/arr061.svg-->
                    <span class="svg-icon svg-icon-1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="black" />
                            <rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="black" />
                        </svg>
                    </span>
                    <!--end::Svg Icon-->
                </div>
                <!--end::Close-->
            </div>
            <!--begin::Modal header-->
            <!--begin::Modal body-->
            <div class="modal-body scroll-y px-10 px-lg-15 pt-0 pb-15">
                <!--begin:Form-->
                <%= form_for(CostCenter.new, local: true, :html => {:id => "kt_modal_new_target_form"} ) do |form| %>
                    <!--begin::Heading-->
                    <div class="mb-13 text-center">
                        <!--begin::Title-->
                        <h1 class="mb-3"> بيانات مركز التكلفة</h1>
                        <!--end::Title-->
                        <!--begin::Description-->
                        <!--<div class="text-muted fw-bold fs-5">أضف مركز تكلفة
                        <a href="#" class="fw-bolder link-primary">جديد</a>.</div>-->
                        <!--end::Description-->
                    </div>
                    <!--end::Heading-->
                    <!--begin::Input group-->
                    <div class="row g-9 mb-8">
                        <!--begin::Col-->
                        <div class="col-md-6 fv-row">
                            <label class="required fs-6 fw-bold mb-2">رمز المركز</label>
                            <input type="text" class="form-control form-control-solid" placeholder="" name="cost_center[code]" />
                        </div>
                        <!--end::Col-->
                        <!--begin::Col-->
                        <div class="col-md-6 fv-row">
                            <label class="fs-6 fw-bold mb-2">الحساب الرئيسى</label>
                            <select name="cost_center[ancestry]" data-control="select2" data-dropdown-parent="#kt_modal_new_target" data-placeholder="اختر" class="form-select form-select-solid">
                                <option value=""><%= t :select%></option>
                                <% @cost_centers.all.each do |cost_center| %>
                                    <option value="<%= cost_center.id%>"><%= cost_center.name_ar%></option>	
                                <% end %>							
                            </select>
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="row g-9 mb-8">
                        <!--begin::Col-->
                        <div class="col-md-6 fv-row">
                            <label class="required fs-6 fw-bold mb-2">اسم المركز</label>
                            <input type="text" class="form-control form-control-solid" placeholder="" name="cost_center[name_ar]" />
                        </div>
                        <!--end::Col-->
                        <!--begin::Col-->
                        <div class="col-md-6 fv-row">
                            <label class="required fs-6 fw-bold mb-2">الاسم اللاتينى</label>
                            <input type="text" class="form-control form-control-solid" placeholder="" name="cost_center[name_en]" />
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Input group-->
                    <!--begin::Input group-->
                    <div class="d-flex flex-column mb-8">
                        <label class="fs-6 fw-bold mb-2">ملاحظات</label>
                        <textarea class="form-control form-control-solid" rows="2" name="cost_center[notes]" placeholder=""></textarea>
                    </div>
                    <!--end::Input group-->
                    
                    
                    
                    
                   
                   
                    
                    <!--begin::Actions-->
                    <div class="text-center">
                        <button type="reset" id="kt_modal_new_target_cancel" class="btn btn-light me-3">إغلاق</button>
                        <button type="button" id="kt_modal_new_target_submit" class="btn btn-primary">
                            <span class="indicator-label">إضافة</span>
                            <span class="indicator-progress">Please wait...
                            <span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
                        </button>
                    </div>
                    <!--end::Actions-->
                <% end %>
                <!--end:Form-->
            </div>
            <!--end::Modal body-->
        </div>
        <!--end::Modal content-->
    </div>
    <!--end::Modal dialog-->
</div>
<!--end::Modal - New Target-->




<p style="color: green"><%= notice %></p>

app/views/cost_centers/new.html.erb
<h1>New cost center</h1>

<%= render "form", cost_center: @cost_center %>

<br>

<div>
  <%= link_to "Back to cost centers", cost_centers_path %>
</div>

app/views/cost_centers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cost_center %>

<div>
  <%= link_to "Edit this cost center", edit_cost_center_path(@cost_center) %> |
  <%= link_to "Back to cost centers", cost_centers_path %>

  <%= button_to "Destroy this cost center", @cost_center, method: :delete %>
</div>